Repository devonfw/devon4j, pull requests merged in 2019-04, with the labels that each got.

#64 JAVA 8 New Date/Time API- mtsj #152
  modules/json/pom.xml
  modules/json/src/main/java/com/devonfw/module/json/common/base/ObjectMapperFactory.java
  templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/config/ApplicationObjectMapperFactory.java
  templates/server/src/main/resources/archetype-resources/core/src/main/resources/config/app/common/dozer-mapping.xml
Labels: JSON, common

#66 #65: disabled open-session-in-view antipattern
  templates/server/src/main/resources/archetype-resources/core/src/main/resources/application.properties
Labels: configuration, dataaccess, enhancement

#75 Added Maven version placeholders
  .mvn/maven.config
  pom.xml
Labels: enhancement
