Repository devonfw/devon4j, pull requests merged in 2020-09, with the labels that each got.

#290 #289: update travis dist to bionic
  .travis.yml
Labels: SCM, enhancement, security

#291 #287: update spring-boot to 2.3.3
  pom.xml
Labels: SCM, enhancement, security, spring, update

#292 #288: update jackson to 2.11.2
  pom.xml
Labels: SCM, enhancement, security, update

#304 Fix macros shown on devonfw.com
  documentation/devon4j.asciidoc
Labels: documentation, enhancement
